version: '3'
services:
  nginx: 
    image: nginx
    ports: "8080:80"
  cache:
    image: redis:4.0.8-alpine
    ports: 
      - "6379:6379"
    networks: 
      - br0
  web:
    build: ./app1
    ports:
      - "9000:80"
    volumes:
      - ./app1:/var/www/app1
      - /var/www/app1/node_modules
      - /var/www/app1/.next
    command: ["pm2-runtime", "process.yml"]
  api:
    build: ./app2
    volumes:
      - ./app2:/var/www/app2
      - /var/www/app2/node_modules
    ports:
      - "9010:80"
    depends_on:
      - "cache"
    command: ["pm2-runtime", "process.yml"]
