version: '3'
services:
  cache1:
    image: redis:4.0.8-alpine
    ports: 
      - "6379:6379"
    networks: 
      - br0
  web1:
    build: ./app1
    volumes:
        - ./app1:/var/www/app1
        - /var/www/app1/node_modules
    ports:
      - "8080:8080"
    networks: 
      - br0
    command: ["pm2-runtime", "process.yml"]
  api1:
    build: ./app2
    command: ["pm2-runtime", "process.yml"]
    volumes:
        - ./app2:/var/www/app2
        - /var/www/app2/node_modules
        - /var/www/app1/.next
    ports:
      - "8090:8090"
    networks: 
      - br0
    depends_on:
      - "cache1"
networks:
    br0:
      external: true