version: '3'
services:
  cache:
    image: redis:4.0.8-alpine
    ports: 
      - "6379:6379"
    networks: 
      - br0
  web:
    build: ./app1
    command: node server.js
    volumes:
      - ./app1:/app1
    ports:
      - "8080:8080"
    networks: 
      - br0
  api:
    build: ./app2
    command: npm run dev
    volumes:
      - ./app2:/app2
    ports:
      - "8090:8090"
    networks: 
      - br0
    depends_on:
      - "cache"
networks:
    br0:
      external: true